### ISSUE TITLE
single trace with multiple span ids

### ISSUE THREAD

**Issue by Parag08** [paolochiodi/zipkin-simple#9]
A single trace can have multiple spans running in different services. How should I achieve this using this library.

**Comment by paolochiodi** [comment]
Hi, thank you for getting in touch.

This library is only intended to handle communication with the zipkin server and it doesn't automatically handle the propagation of the span data among multiple services.

To achieve that with this library you should code yourself the sharing of traceData among the services. 
This varies depending on how the services communicate with each other, for http services it is usually done by putting the span and trace ids in headers.

A simpler alternative would be to just use the [official zipkin library](https://github.com/openzipkin/zipkin-js) that includes instrumentations to work with the most common libraries (i.e. express, hapi, postgres, redis...)

**Comment by Parag08** [comment]
Thanks for quick reply I thought i am missing a feature. You can close the issue. I will handle it with my code. Btw thanks for the library. Its a very simplistic implementation. It is much easier to understand and implement as oppose to official one's.

**Comment by paolochiodi** [comment]
@Parag08 Be aware that this implementation is easier, but also way less featured than the official one.
I.e. the original version keeps track of the span data by itself, switching to the correct data per each "http request" and hiding the complexity of using async hooks and monkeys patches.

That's something you'll need to do in your code, although it can be done in a more simplistic way by just adding the data to the request object
